### PR TITLE
Pushes changes upstream from microsoftgraph fork

### PR DESCRIPTION
**Pull request by irvinesunday**
This PR aims to push changes up into the upstream `master` branch from the forked `microsoftgraph` repo. 
The list of changes are outlined below accompanied with their corresponding issues and PRs made in the forked repo.

1. **Adds root path**
- Issue: https://github.com/microsoftgraph/microsoft-graph-explorer-api/issues/239
- PR: https://github.com/microsoftgraph/microsoft-graph-explorer-api/pull/240
2. **Fixes generating of OpenAPI doc. when PrefixEntityTypeNameBeforeKey is enabled**
- Issue: https://github.com/microsoft/OpenAPI.NET.OData/issues/75
- PR: https://github.com/microsoftgraph/OpenAPI.NET.OData/pull/3
3. **Update /$ref update operation from PATCH to PUT (bug fix)**
- Issue: https://github.com/microsoftgraph/microsoft-graph-explorer-api/issues/291
- PR: https://github.com/microsoftgraph/OpenAPI.NET.OData/pull/4
4. **Limit operations to only include item by key for contained collections and $ref for non-contained collections**
- Issue: https://github.com/microsoft/OpenAPI.NET.OData/issues/79
- PR: https://github.com/microsoftgraph/OpenAPI.NET.OData/pull/6
5. **Create stream paths**
- Issue: https://github.com/microsoft/OpenAPI.NET.OData/issues/71 (stream paths)
- PRs
  - https://github.com/microsoftgraph/OpenAPI.NET.OData/pull/5
  - https://github.com/microsoftgraph/OpenAPI.NET.OData/pull/7 (bug fix)
6. **Create media entities**
- Issue: https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_workitems/edit/5853/
- PRs:
   - https://github.com/microsoftgraph/OpenAPI.NET.OData/pull/8
   - https://github.com/microsoftgraph/OpenAPI.NET.OData/pull/10 (bug fix)
   - https://github.com/microsoftgraph/OpenAPI.NET.OData/pull/11 (bug fix)
7. **Supports describing AcceptableMediaTypes from annotations**
- Issue: https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_workitems/edit/5854/
- PR: https://github.com/microsoftgraph/OpenAPI.NET.OData/pull/9
8. **Bumps up Microsoft.OpenAPI library version**
- PR: https://github.com/microsoftgraph/OpenAPI.NET.OData/pull/1

### CODE REVIEW

**Review by xuzhg — APPROVED** [review]

**Comment by xuzhg** [comment]
Merged.

**Comment by unchase** [comment]
Hi, @xuzhg
Can you release this changes into the [nuget package](https://www.nuget.org/packages/Microsoft.OpenApi.OData/)?

**Comment by xuzhg** [comment]
@unchase here we are: https://www.nuget.org/packages/Microsoft.OpenApi.OData/1.0.5

Please let us know any problems and issues. Thanks.

**Comment by unchase** [comment]
> @unchase here we are: https://www.nuget.org/packages/Microsoft.OpenApi.OData/1.0.5
> 
> Please let us know any problems and issues. Thanks.

Thx!

**Pull request closed without merging**
